### ISSUE TITLE
Using docker-compose

### ISSUE THREAD

**Issue by 1beb** [rocker-org/hadleyverse#4]
I'm running a docker-compose.yml setup with this image and it seems that RStudio returns a 502 error. It seems to pull in the `rocker/rstudio` image but not allow one to actually change the username/password. 

Here's an example:  

```
rstudio:
   image: rocker/hadleyverse
   container_name: rstudio
   environment:
   - ROOT=TRUE
   - VIRTUAL_HOST=some.host.tld
   - USER=admin
   - PASSWORD=pass
```

Given that `hadleyverse` builds on top of `rocker/rstudio`, my expectation was that RStudio would be functional. However, I couldn't actually access RStudio from the web using the above after `docker-compose up -d`
